<?php
/**
 * Block Name: Lesson Facilitator Notes
 * Description: Displays the facilitator notes for a lesson.
 *
 * @package wporg
 */

namespace WordPressdotorg\Theme\Learn_2024\Lesson_Facilitator_Notes;

use Error;
use function WPOrg_Learn\{get_build_path};

defined( 'WPINC' ) || die();

/**
 * Actions and filters.
 */
add_action( 'init', __NAMESPACE__ . '\init' );

/**
 * Add a script to control elements in the sensei lesson facilitator notes pattern.
 *
 * The dependencies are autogenerated in block.json, and can be read with
 * `wp_json_file_decode` & `register_block_script_handle.
 */
function init() {
	register_block_type(
		dirname( dirname( __DIR__ ) ) . '/build/lesson-facilitator-notes',
		array(
			'render_callback' => __NAMESPACE__ . '\render',
		)
	);
}

/**
 * Render the block content.
 *
 * @param array    $attributes Block attributes.
 * @param string   $content    Block default content.
 * @param WP_Block $block      Block instance.
 *
 * @throws Error If the script asset file is not readable.
 * @return string Returns the block markup.
 */
function render( $attributes, $content, $block ) {
	$script_asset_path = get_stylesheet_directory() . '/build/lesson-facilitator-notes/index.asset.php';
	if ( ! is_readable( $script_asset_path ) ) {
		throw new Error(
			'You need to run `yarn start` or `yarn run build` for the "wporg-learn/lesson-facilitator-notes" block first.'
		);
	}

	if ( empty( $attributes['lessonPlanId'] ) ) {
		return;
	}

	$lesson_plan = get_post( $attributes['lessonPlanId'] );

	if ( ! $lesson_plan ) {
		return;
	}

	$lesson_plan_url = get_permalink( $lesson_plan->ID );
	return sprintf(
		// If changing classname here, you'd also need to update it in style.scss and view.js.
		'<div class="wporg-learn-lesson-facilitator-notes-label"><a href="%s" target="_blank">%s</a></div>',
		esc_url( $lesson_plan_url ),
		esc_html__( 'Facilitator Note', 'wporg-learn' )
	);
}
