<?php
/**
 *  Adds scripts for sensei-lesson-facilitator-notes pattern.
 */

namespace WordPressdotorg\Theme\Learn_2024\Lesson_Facilitator_Notes;

defined( 'WPINC' ) || die();

/**
 * Actions and filters.
 */
add_action( 'init', __NAMESPACE__ . '\init' );

/**
 * Add a script to control elements in the sensei lesson facilitator notes pattern.
 *
 * The dependencies are autogenerated in block.json, and can be read with
 * `wp_json_file_decode` & `register_block_script_handle.
 */
function init() {
	$metadata_file = dirname( dirname( __DIR__ ) ) . '/build/lesson-facilitator-notes/block.json';
	$metadata = wp_json_file_decode( $metadata_file, array( 'associative' => true ) );
	$metadata['file'] = $metadata_file;

	$script_handle = register_block_script_handle( $metadata, 'viewScript', 0 );

	// Enqueue the assets when the  sensei lesson facilitator notes pattern is on the page.
	add_action(
		'render_block_core/pattern',
		function( $block_content, $block ) use ( $script_handle ) {
			if ( isset( $block['attrs']['slug'] ) && 'wporg-learn-2024/sensei-lesson-facilitator-notes' === $block['attrs']['slug'] ) {
				wp_enqueue_script( $script_handle );
			}
			return $block_content;
		},
		10,
		2
	);
}
