<?php
/**
 * Adds aria labels to the Sensei progress bars.
 */

namespace WordPressdotorg\Theme\Learn_2024\Sensei_Progress_Bar;

defined( 'WPINC' ) || die();

/**
 * Actions and filters.
 */
add_action( 'init', __NAMESPACE__ . '\init' );

/**
 * Add the scripts to update the Sensei progress bar block.
 *
 * The dependencies are autogenerated in block.json, and can be read with
 * `wp_json_file_decode` & `register_block_script_handle.
 */
function init() {
	$metadata_file = dirname( dirname( __DIR__ ) ) . '/build/sensei-progress-bar/block.json';
	$metadata = wp_json_file_decode( $metadata_file, array( 'associative' => true ) );
	$metadata['file'] = $metadata_file;

	$script_handle = register_block_script_handle( $metadata, 'viewScript', 0 );

	// Enqueue the assets only when the Sensei progress bar block is on the page.
	add_action(
		'render_block_sensei-lms/course-progress',
		function( $block_content ) use ( $script_handle ) {
			wp_enqueue_script( $script_handle );
			return $block_content;
		}
	);
}
