<?php
/**
 * Extends the core code block to add copy & expand buttons.
 */

namespace WordPressdotorg\Theme\Learn_2024\Code_Block;

defined( 'WPINC' ) || die();

/**
 * Actions and filters.
 */
add_action( 'init', __NAMESPACE__ . '\init' );

/**
 * Add the scripts & styles to update the code block.
 *
 * The dependencies are autogenerated in block.json, and can be read with
 * `wp_json_file_decode` & `register_block_script_handle.
 */
function init() {
	$metadata_file = dirname( dirname( __DIR__ ) ) . '/build/code/block.json';
	$metadata = wp_json_file_decode( $metadata_file, array( 'associative' => true ) );
	$metadata['file'] = $metadata_file;

	$style_handle = register_block_style_handle( $metadata, 'style', 0 );

	$script_handle = register_block_script_handle( $metadata, 'viewScript', 0 );
	wp_localize_script(
		$script_handle,
		'wporgCodeI18n',
		array(
			'copy'   => __( 'Copy', 'wporg-learn' ),
			'copied' => __( 'Code copied', 'wporg-learn' ),
			'expand'   => __( 'Expand code', 'wporg-learn' ),
			'collapse' => __( 'Collapse code', 'wporg-learn' ),
		)
	);

	// Enqueue the assets only when the code block is on the page.
	add_action(
		'render_block_core/code',
		function( $block_content ) use ( $script_handle, $style_handle ) {
			wp_enqueue_script( $script_handle );
			wp_enqueue_style( $style_handle );
			return $block_content;
		}
	);
}
