# Uses https://github.com/marketplace/actions/add-to-github-projects
# Based on https://github.com/WordPress/Documentation-Issue-Tracker/blob/main/.github/workflows/add-to-project.yml


name: Add issues to GitHub projects

on:
  issues:
    types:
      - labeled
      
# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  add-to-web-development-project:
    name: Add issues labeled "[Type] Bug" to web development project
    runs-on: ubuntu-latest
    permissions:
      issues: read    # Required to read issue data
      projects: write # Required to add issues to the GitHub project
    steps:
      - uses: actions/add-to-project@v0.5.0
        if: contains(github.event.issue.labels.*.name, 'Awaiting Triage')
        with:
          project-url: https://github.com/orgs/WordPress/projects/71
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: "[Type] Bug"
 
  add-to-content-feedback-project:
    name: Add issues labeled "Content Feedback" to LearnWP Content - Feedback project
    runs-on: ubuntu-latest
    permissions:
      issues: read    # Required to read issue data
      projects: write # Required to add issues to the GitHub project
    steps:
      - uses: actions/add-to-project@v0.5.0
        if: contains(github.event.issue.labels.*.name, 'Awaiting Triage')
        with:
          project-url: https://github.com/orgs/WordPress/projects/78
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: Content Feedback
          
  add-to-admin-project:
    name: Add handbook issues to Training Team Administration project
    runs-on: ubuntu-latest
    permissions:
      issues: read    # Required to read issue data
      projects: write # Required to add issues to the GitHub project
    steps:
      - uses: actions/add-to-project@v0.5.0
        if: contains(github.event.issue.labels.*.name, 'Awaiting Triage') || contains(github.event.issue.labels.*.name, '[Admin] Meeting Agenda')
        with:
          project-url: https://github.com/orgs/WordPress/projects/53/views/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: "[Admin] Handbook"

