<?php
/**
 * Enhance accessibility for the sensei lesson actions
 */

namespace WordPressdotorg\Theme\Learn_2024\Sensei_Lesson_Actions_A11y;

defined( 'WPINC' ) || die();

/**
 * Actions and filters.
 */
add_action( 'init', __NAMESPACE__ . '\init' );

/**
 * Add the scripts to update the sensei lesson actions block.
 *
 * The dependencies are autogenerated in block.json, and can be read with
 * `wp_json_file_decode` & `register_block_script_handle.
 */
function init() {
	$metadata_file = dirname( dirname( __DIR__ ) ) . '/build/sensei-lesson-actions-a11y/block.json';
	$metadata = wp_json_file_decode( $metadata_file, array( 'associative' => true ) );
	$metadata['file'] = $metadata_file;

	$script_handle = register_block_script_handle( $metadata, 'viewScript', 0 );

	// Enqueue the assets when the single lesson content pattern is on the page.
	add_action(
		'render_block_core/pattern',
		function( $block_content, $block ) use ( $script_handle ) {
			if ( isset( $block['attrs']['slug'] ) && 'wporg-learn-2024/single-lesson-content' === $block['attrs']['slug'] ) {
				wp_enqueue_script( $script_handle );
			}
			return $block_content;
		},
		10,
		2
	);
}
