-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: db2.ord.wordpress.org:3306
-- Generation Time: Nov 24, 2020 at 12:26 AM
-- Server version: 10.2.33-MariaDB-log
-- PHP Version: 7.4.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `wordpress`
--

-- --------------------------------------------------------

--
-- Table structure for table `wporg_events`
--

CREATE TABLE `wporg_events` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `type` varchar(32) NOT NULL DEFAULT '',
  `source_id` varchar(32) NOT NULL DEFAULT '',
  `status` varchar(16) NOT NULL,
  `title` varchar(255) NOT NULL DEFAULT '',
  `url` text NOT NULL,
  `description` longtext DEFAULT NULL,
  `attendees` int(11) UNSIGNED DEFAULT NULL,
  `meetup` varchar(255) DEFAULT NULL,
  `meetup_url` text DEFAULT NULL,
  `date_utc` datetime NOT NULL,
  `date_utc_offset` varchar(32) DEFAULT NULL,
  `end_date` datetime NOT NULL,
  `location` text DEFAULT NULL,
  `country` varchar(64) DEFAULT NULL,
  `latitude` double NOT NULL,
  `longitude` double NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `wporg_events`
--

INSERT INTO `wporg_events` (`id`, `type`, `source_id`, `status`, `title`, `url`, `description`, `attendees`, `meetup`, `meetup_url`, `date_utc`, `date_utc_offset`, `end_date`, `location`, `country`, `latitude`, `longitude`) VALUES
(50012648, 'meetup', '272512607', 'scheduled', 'Discussion Group: Introduction to Contributing to WordPress', 'https://www.meetup.com/learn-wordpress-discussions/events/272512607/', '<p>Join us for a discussion on this workshop: An Introduction to the WordPress Open-Source Project!</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/an-introduction-to-the-wordpress-open-source-project/\" class=\"linkified\">https://learn.wordpress.org/workshop/an-introduction-to-the-wordpress-open-source-project/</a>.</p> <p>Even if you are brand new to Open Source and the WordPress Project, you are welcome to participate! Bring your questions, your thoughts, comments to this informal discussion.</p> <p>For more information, visit <a href=\"https://make.wordpress.org/community/\" class=\"linkified\">https://make.wordpress.org/community/</a></p> ', 26, 'Learn WordPress', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-08-13 14:00:00', '-25200', '2020-08-13 15:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(50211842, 'meetup', '272511923', 'scheduled', 'Discussion Group: Introduction to Contributing to WordPress', 'https://www.meetup.com/learn-wordpress-discussions/events/272511923/', '<p>Join us for a discussion on this workshop: An Introduction to the WordPress Open-Source Project!</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/an-introduction-to-the-wordpress-open-source-project/\" class=\"linkified\">https://learn.wordpress.org/workshop/an-introduction-to-the-wordpress-open-source-project/</a>.</p> <p>Even if you are brand new to Open Source and the WordPress Project, you are welcome to participate! Bring your questions, your thoughts, comments to this informal discussion.</p> <p>For more information, visit <a href=\"https://make.wordpress.org/community/\" class=\"linkified\">https://make.wordpress.org/community/</a></p> ', 126, 'Learn WordPress', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-08-18 09:00:00', '-25200', '2020-08-18 10:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(50289174, 'meetup', '272503390', 'scheduled', 'Discussion Group: Intro to Gutenberg Block Development', 'https://www.meetup.com/learn-wordpress-discussions/events/272503390/', '<p>Join us for a discussion on this workshop: Intro to Gutenberg Block Development!</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/intro-to-gutenberg-block-development/\" class=\"linkified\">https://learn.wordpress.org/workshop/intro-to-gutenberg-block-development/</a>.</p> <p>Even if you are brand new to block development and Gutenberg, you are welcome to participate! Bring your questions, thoughts, and comments to this informal discussion hosted by Jonathan Bossenger.</p> ', 58, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-08-20 06:00:00', '-25200', '2020-08-20 07:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(50290924, 'meetup', '272502588', 'scheduled', 'Discussion Group: Introduction to Contributing to WordPress', 'https://www.meetup.com/learn-wordpress-discussions/events/272502588/', '<p>Join us for a discussion on this workshop: An Introduction to the WordPress Open-Source Project!</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/an-introduction-to-the-wordpress-open-source-project/\" class=\"linkified\">https://learn.wordpress.org/workshop/an-introduction-to-the-wordpress-open-source-project/</a>.</p> <p>Even if you are brand new to Open Source and the WordPress Project, you are welcome to participate! Bring your questions, your thoughts, comments to this informal discussion.</p> <p>For more information, visit <a href=\"https://make.wordpress.org/community/\" class=\"linkified\">https://make.wordpress.org/community/</a></p> ', 10, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-08-20 07:00:00', '-25200', '2020-08-20 08:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(50332452, 'meetup', '272504942', 'scheduled', 'Discussion Group: Intro to Publishing with the Block Editor', 'https://www.meetup.com/learn-wordpress-discussions/events/272504942/', '<p>Join us for a discussion on this workshop: Intro to Publishing with the Block Editor!</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/intro-to-publishing-with-the-block-editor/\" class=\"linkified\">https://learn.wordpress.org/workshop/intro-to-publishing-with-the-block-editor/</a></p> <p>This workshop is geared toward new and experienced publishers alike, looking to learn more about using the block editor. Bring your questions, thoughts, and comments to this informal discussion.</p> ', 25, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-08-21 07:00:00', '-25200', '2020-08-21 08:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(50572737, 'meetup', '272503835', 'scheduled', 'Discussion Group: Introduction to Open-Source', 'https://www.meetup.com/learn-wordpress-discussions/events/272503835/', '<p>Join us for a discussion on this workshop: Introduction to Open-source.</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/introduction-to-open-source/\" class=\"linkified\">https://learn.wordpress.org/workshop/introduction-to-open-source/</a>.</p> <p>Even if you are brand new to open-source and WordPress, you are welcome to participate! Bring your questions, thoughts, and comments to this informal discussion hosted by Hari Shanker.</p> ', 103, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-08-27 05:00:00', '-25200', '2020-08-27 06:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(50846143, 'meetup', '272502647', 'scheduled', 'Discussion Group: Introduction to Contributing to WordPress', 'https://www.meetup.com/learn-wordpress-discussions/events/272502647/', '<p>Join us for a discussion on this workshop: An Introduction to the WordPress Open-Source Project!</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/an-introduction-to-the-wordpress-open-source-project/\" class=\"linkified\">https://learn.wordpress.org/workshop/an-introduction-to-the-wordpress-open-source-project/</a>.</p> <p>Even if you are brand new to Open Source and the WordPress Project, you are welcome to participate! Bring your questions, your thoughts, comments to this informal discussion.</p> <p>For more information, visit <a href=\"https://make.wordpress.org/community/\" class=\"linkified\">https://make.wordpress.org/community/</a></p> ', 107, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-09-03 01:00:00', '-25200', '2020-09-03 02:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(50889496, 'meetup', '272504259', 'scheduled', 'Discussion Group: Introduction to Open-Source', 'https://www.meetup.com/learn-wordpress-discussions/events/272504259/', '<p>Join us for a discussion on this workshop: Introduction to Open-source.</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/introduction-to-open-source/\" class=\"linkified\">https://learn.wordpress.org/workshop/introduction-to-open-source/</a>.</p> <p>Even if you are brand new to open-source and WordPress, you are welcome to participate! Bring your questions, thoughts, and comments to this informal discussion hosted by Hari Shanker.</p> ', 21, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-09-04 03:00:00', '-25200', '2020-09-04 04:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(51015361, 'meetup', '272504968', 'scheduled', 'Discussion Group: Intro to Publishing with the Block Editor', 'https://www.meetup.com/learn-wordpress-discussions/events/272504968/', '<p>Join us for a discussion on this workshop: Intro to Publishing with the Block Editor!</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/intro-to-publishing-with-the-block-editor/\" class=\"linkified\">https://learn.wordpress.org/workshop/intro-to-publishing-with-the-block-editor/</a></p> <p>This workshop is geared toward new and experienced publishers alike, looking to learn more about using the block editor. Bring your questions, thoughts, and comments to this informal discussion.</p> ', 25, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-09-07 07:00:00', '-25200', '2020-09-07 08:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52068668, 'meetup', '273614907', 'scheduled', 'Discussion Group: WordPress Troubleshooting Basics: Part 1', 'https://www.meetup.com/learn-wordpress-discussions/events/273614907/', '<p>Join us for a discussion on this workshop: WordPress Troubleshooting Basics: Part 1.</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-1/\" class=\"linkified\">https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-1/</a></p> <p>This workshop covers the basics of WordPress troubleshooting. It is aimed at a beginner audience and will cover the strategy to troubleshoot WordPress issues, along with some common troubleshooting steps that will help in fixing many common WordPress issues.</p> <p>Please watch the video first and join us for a discussion to answer any questions that you have on translating WordPress.</p> ', 74, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-06 06:00:00', '-25200', '2020-10-06 07:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52074930, 'meetup', '273494801', 'scheduled', 'Discussion Group: Who am I to be speaking? + Finding a topic for a WP event', 'https://www.meetup.com/learn-wordpress-discussions/events/273494801/', '<p>If you are from a marginalized or underrepresented group in WordPress in terms of gender, race, class, sexuality, ability, age, etc. join us for a discussion on this workshop: Who am I to be speaking + Finding a topic.</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-1/\" class=\"linkified\">https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-1/</a></p> <p>We invite you to do the exercises along with the video, and bring your answers to the discussion group to get feedback.</p> <p>This workshop is geared towards people from marginalized or underrepresented groups in WordPress who are intrigued by the idea of speaking at an online WordPress event. The focus is to look at what has stopped you from speaking in the past and explore how to move past your fears, generate WordPress-related topics to give a talk on, and boost your speaking confidence.</p> <p>You can join this discussion on its own or with the other 2 discussions of this series this week. It is the same zoom link for all 3.</p> ', 21, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-06 10:00:00', '-25200', '2020-10-06 11:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52115696, 'meetup', '273494834', 'scheduled', 'Discussion Group: Writing a pitch for being accepted to speak at a WP event', 'https://www.meetup.com/learn-wordpress-discussions/events/273494834/', '<p>If you are from a marginalized or underrepresented group in WordPress in terms of gender, race, class, sexuality, ability, age, etc. join us for a discussion on this workshop: Writing a pitch</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-2/\" class=\"linkified\">https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-2/</a></p> <p>We invite you to do the exercises along with the video, and bring your title, pitch, and bio to the discussion group to get feedback.</p> <p>This workshop is geared towards people from marginalized or underrepresented groups in WordPress who are intrigued by the idea of speaking at an online WordPress event. The focus is to look at creating a workshop description (aka pitch) and bio that has a higher chance of being accepted by speaker selection committees.</p> <p>You can join this discussion on its own or with the other 2 discussions of this series this week. It is the same zoom link for all 3.</p> ', 17, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-07 10:00:00', '-25200', '2020-10-07 11:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52153327, 'meetup', '273494869', 'scheduled', 'Discussion Group: Online Stage Presence for speaking at WordPress events', 'https://www.meetup.com/learn-wordpress-discussions/events/273494869/', '<p>If you are from a marginalized or underrepresented group in WordPress in terms of gender, race, class, sexuality, ability, age, etc. join us for a discussion on this workshop: Online Stage Presence</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/online-stage-presence/\" class=\"linkified\">https://learn.wordpress.org/workshop/online-stage-presence/</a></p> <p>This workshop is geared towards people from marginalized or underrepresented groups in WordPress who are intrigued by the idea of speaking at an online WordPress event. The focus is to have better stage presence â€“ in general for any stage, as well as specifically for presenting from your computer for online events.</p> <p>You can join this discussion on its own or with the other 2 discussions of this series this week. It is the same zoom link for all 3.</p> ', 19, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-08 10:00:00', '-25200', '2020-10-08 11:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52298761, 'meetup', '273798318', 'scheduled', 'Discussion Group: Who am I to be speaking? + Finding a topic for a WP event', 'https://www.meetup.com/learn-wordpress-discussions/events/273798318/', '<p>If you are from a marginalized or underrepresented group in WordPress in terms of gender, race, class, sexuality, ability, age, etc. join us for a discussion on this workshop: Who am I to be speaking + Finding a topic.</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-1/\" class=\"linkified\">https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-1/</a></p> <p>We invite you to do the exercises along with the video, and bring your answers to the discussion group to get feedback.</p> <p>This workshop is geared towards people from marginalized or underrepresented groups in WordPress who are intrigued by the idea of speaking at an online WordPress event. The focus is to look at what has stopped you from speaking in the past and explore how to move past your fears, generate WordPress-related topics to give a talk on, and boost your speaking confidence.</p> ', 24, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-12 07:00:00', '-25200', '2020-10-12 08:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52349401, 'meetup', '273834007', 'scheduled', 'Discussion: Introduction to Contributing to the WordPress Open Source Project', 'https://www.meetup.com/learn-wordpress-discussions/events/273834007/', '<p>Join us for a discussion on this workshop: Introduction to Contributing to WordPress.</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. Sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance:<br/><a href=\"https://learn.wordpress.org/workshop/an-introduction-to-contributing/\" class=\"linkified\">https://learn.wordpress.org/workshop/an-introduction-to-contributing/</a></p> <p>Even if you are brand new to open-source and WordPress, you are welcome to participate! Bring your questions, thoughts, and comments to this informal discussion hosted by Courtney P.K.</p> ', 17, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-13 16:00:00', '-25200', '2020-10-13 17:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52376274, 'meetup', '273756574', 'scheduled', 'Discussion Group: Intro to Publishing with the Block Editor', 'https://www.meetup.com/learn-wordpress-discussions/events/273756574/', '<p>Join us for a discussion on this workshop: Intro to Publishing with the Block Editor!</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/intro-to-publishing-with-the-block-editor/\" class=\"linkified\">https://learn.wordpress.org/workshop/intro-to-publishing-with-the-block-editor/</a></p> <p>This workshop is geared toward new and experienced publishers alike, looking to learn more about using the block editor. Bring your questions, thoughts, and comments to this informal discussion.</p> ', 23, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-14 09:00:00', '-25200', '2020-10-14 10:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52415632, 'meetup', '273888578', 'scheduled', 'Discussion: Introduction to Contributing to the WordPress Open Source Project', 'https://www.meetup.com/learn-wordpress-discussions/events/273888578/', '<p>Join us for a discussion on this workshop: Introduction to Contributing to WordPress.</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. Sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance:<br/><a href=\"https://learn.wordpress.org/workshop/an-introduction-to-contributing/\" class=\"linkified\">https://learn.wordpress.org/workshop/an-introduction-to-contributing/</a></p> <p>Even if you are brand new to open-source and WordPress, you are welcome to participate! Bring your questions, thoughts, and comments to this informal discussion hosted by Cami Kaos.</p> ', 17, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-15 10:00:00', '-25200', '2020-10-15 11:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52473439, 'meetup', '273615019', 'scheduled', 'Discussion Group: WordPress Troubleshooting Basics: Part 1', 'https://www.meetup.com/learn-wordpress-discussions/events/273615019/', '<p>Join us for a discussion on this workshop: WordPress Troubleshooting Basics: Part 1.</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-1/\" class=\"linkified\">https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-1/</a></p> <p>This workshop covers the basics of WordPress troubleshooting. It is aimed at a beginner audience and will cover the strategy to troubleshoot WordPress issues, along with some common troubleshooting steps that will help in fixing many common WordPress issues.</p> <p>Please watch the video first and join us for a discussion to answer any questions that you have on translating WordPress.</p> ', 43, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-16 23:30:00', '-25200', '2020-10-17 00:30:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52558968, 'meetup', '273798352', 'scheduled', 'Discussion Group: Writing a pitch for being accepted to speak at a WP event', 'https://www.meetup.com/learn-wordpress-discussions/events/273798352/', '<p>If you are from a marginalized or underrepresented group in WordPress in terms of gender, race, class, sexuality, ability, age, etc. join us for a discussion on this workshop: Writing a pitch</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-2/\" class=\"linkified\">https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-2/</a></p> <p>We invite you to do the exercises along with the video, and bring your title, pitch, and bio to the discussion group to get feedback.</p> <p>This workshop is geared towards people from marginalized or underrepresented groups in WordPress who are intrigued by the idea of speaking at an online WordPress event. The focus is to look at creating a workshop description (aka pitch) and bio that has a higher chance of being accepted by speaker selection committees.</p> ', 18, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-19 07:00:00', '-25200', '2020-10-19 08:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52630909, 'meetup', '273756735', 'scheduled', 'Discussion Group: Introduction to Open-Source', 'https://www.meetup.com/learn-wordpress-discussions/events/273756735/', '<p>Join us for a discussion on this workshop: Introduction to Open-source.</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. Sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/introduction-to-open-source/\" class=\"linkified\">https://learn.wordpress.org/workshop/introduction-to-open-source/</a></p> <p>Even if you are brand new to open-source and WordPress, you are welcome to participate! Bring your questions, thoughts, and comments to this informal discussion hosted by Hari Shanker and Erica Varlese.</p> ', 28, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-21 05:00:00', '-25200', '2020-10-21 06:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52644967, 'meetup', '274061876', 'scheduled', 'Discussion Group:  Contributing on the WordPress Community Team', 'https://www.meetup.com/learn-wordpress-discussions/events/274061876/', '<p>Join us for a discussion on this workshop: Contributing on the WordPress Community Team!</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/contributing-on-the-wordpress-community-team/\" class=\"linkified\">https://learn.wordpress.org/workshop/contributing-on-the-wordpress-community-team/</a></p> <p>Even if you are brand new to the WordPress Community, you are welcome to participate! Bring your questions, your thoughts, comments to this informal discussion.</p> <p>For more information, visit <a href=\"https://make.wordpress.org/community/\" class=\"linkified\">https://make.wordpress.org/community/</a></p> ', 9, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-21 14:00:00', '-25200', '2020-10-21 15:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52701133, 'meetup', '273993927', 'scheduled', 'Discussion Group: WordPress Troubleshooting Basics: Part 1', 'https://www.meetup.com/learn-wordpress-discussions/events/273993927/', '<p>Join us for a discussion on this workshop: WordPress Troubleshooting Basics: Part 1.</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-1/\" class=\"linkified\">https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-1/</a></p> <p>This workshop covers the basics of WordPress troubleshooting. It is aimed at a beginner audience and will cover the strategy to troubleshoot WordPress issues, along with some common troubleshooting steps that will help in fixing many common WordPress issues.</p> <p>Please watch the video first and join us for a discussion to answer any questions that you have on troubleshooting WordPress.</p> ', 44, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-23 06:00:00', '-25200', '2020-10-23 07:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52814008, 'meetup', '273798367', 'scheduled', 'Discussion Group: Who am I to be speaking? + Finding a topic for a WP event', 'https://www.meetup.com/learn-wordpress-discussions/events/273798367/', '<p>If you are from a marginalized or underrepresented group in WordPress in terms of gender, race, class, sexuality, ability, age, etc. join us for a discussion on this workshop: Who am I to be speaking + Finding a topic.</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-1/\" class=\"linkified\">https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-1/</a></p> <p>We invite you to do the exercises along with the video, and bring your answers to the discussion group to get feedback.</p> <p>This workshop is geared towards people from marginalized or underrepresented groups in WordPress who are intrigued by the idea of speaking at an online WordPress event. The focus is to look at what has stopped you from speaking in the past and explore how to move past your fears, generate WordPress-related topics to give a talk on, and boost your speaking confidence.</p> ', 26, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-26 07:00:00', '-25200', '2020-10-26 08:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52866280, 'meetup', '274133899', 'scheduled', 'Discussion Group:  Contributing on the WordPress Community Team', 'https://www.meetup.com/learn-wordpress-discussions/events/274133899/', '<p>Join us for a discussion on this workshop: Contributing on the WordPress Community Team!</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. Sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/contributing-on-the-wordpress-community-team/\" class=\"linkified\">https://learn.wordpress.org/workshop/contributing-on-the-wordpress-community-team/</a></p> <p>Even if you are brand new to the WordPress Community, you are welcome to participate! Bring your questions, your thoughts, comments to this informal discussion.</p> <p>For more information, visit <a href=\"https://make.wordpress.org/community/\" class=\"linkified\">https://make.wordpress.org/community/</a></p> ', 11, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-27 15:30:00', '-25200', '2020-10-27 16:30:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52891485, 'meetup', '274057640', 'scheduled', 'Discussion Group: Intro to Publishing with the Block Editor', 'https://www.meetup.com/learn-wordpress-discussions/events/274057640/', '<p>Join us for a discussion on this workshop: Intro to Publishing with the Block Editor!</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/intro-to-publishing-with-the-block-editor/\" class=\"linkified\">https://learn.wordpress.org/workshop/intro-to-publishing-with-the-block-editor/</a></p> <p>This workshop is geared toward new and experienced publishers alike, looking to learn more about using the block editor. Bring your questions, thoughts, and comments to this informal discussion.</p> ', 21, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-28 08:00:00', '-25200', '2020-10-28 09:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52924505, 'meetup', '274203044', 'scheduled', 'Discussion group: Organizing WordPress Meetups - Getting Started', 'https://www.meetup.com/learn-wordpress-discussions/events/274203044/', '<p>Join us for a discussion on this workshop: Organizing WordPress Meetups - Getting Started!</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. In case you don\'t have an account already, sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/organizing-wordpress-meetups-getting-started/\" class=\"linkified\">https://learn.wordpress.org/workshop/organizing-wordpress-meetups-getting-started/</a></p> <p>This workshop is geared toward at all WordPress Community members that wish to be a part of the WordPress community, to organize a WordPress meetup. You can join the discussion group even if you are an experienced community organizer.</p> <p>Bring us all the questions you have, and we\'re happy to answer all questions you have!</p> ', 15, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-29 05:00:00', '-25200', '2020-10-29 06:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(52932353, 'meetup', '274187617', 'scheduled', 'Discussion Group:  Contributing on the WordPress Community Team', 'https://www.meetup.com/learn-wordpress-discussions/events/274187617/', '<p>Join us for a discussion on this workshop: Contributing on the WordPress Community Team!</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. Sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/contributing-on-the-wordpress-community-team/\" class=\"linkified\">https://learn.wordpress.org/workshop/contributing-on-the-wordpress-community-team/</a></p> <p>Even if you are brand new to the WordPress Community, you are welcome to participate! Bring your questions, your thoughts, comments to this informal discussion.</p> <p>For more information, visit <a href=\"https://make.wordpress.org/community/\" class=\"linkified\">https://make.wordpress.org/community/</a></p> ', 7, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-10-29 10:00:00', '-25200', '2020-10-29 11:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53061774, 'meetup', '274203124', 'scheduled', 'Discussion group: Organizing WordPress Meetups - Getting Started', 'https://www.meetup.com/learn-wordpress-discussions/events/274203124/', '<p>Join us for a discussion on this workshop: Organizing WordPress Meetups - Getting Started!</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. In case you don\'t have an account already, sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/organizing-wordpress-meetups-getting-started/\" class=\"linkified\">https://learn.wordpress.org/workshop/organizing-wordpress-meetups-getting-started/</a></p> <p>This workshop is geared toward at all WordPress Community members that wish to be a part of the WordPress community, to organize a WordPress meetup. You can join the discussion group even if you are an experienced community organizer.</p> <p>Bring us all the questions you have, and we\'re happy to answer all questions you have!</p> ', 40, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-02 05:00:00', '-28800', '2020-11-02 06:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53107048, 'meetup', '274264584', 'scheduled', 'Discussion group: Organizing WordPress Meetups - Getting Started', 'https://www.meetup.com/learn-wordpress-discussions/events/274264584/', '<p>Join us for a discussion on this workshop: Organizing WordPress Meetups - Getting Started!</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. In case you don\'t have an account already, sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/organizing-wordpress-meetups-getting-started/\" class=\"linkified\">https://learn.wordpress.org/workshop/organizing-wordpress-meetups-getting-started/</a></p> <p>This workshop is geared toward at all WordPress Community members that wish to be a part of the WordPress community, to organize a WordPress meetup. You can join the discussion group even if you are an experienced community organizer.</p> <p>Bring us all the questions you have, and we\'re happy to answer all questions you have!</p> ', 14, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-03 10:00:00', '-28800', '2020-11-03 11:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53179139, 'meetup', '274257974', 'scheduled', 'Discussion: Introduction to Contributing to the WordPress Open Source Project', 'https://www.meetup.com/learn-wordpress-discussions/events/274257974/', '<p>Join us for a discussion on this workshop: Introduction to Contributing to WordPress.</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. Sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance:<br/><a href=\"https://learn.wordpress.org/workshop/an-introduction-to-contributing/\" class=\"linkified\">https://learn.wordpress.org/workshop/an-introduction-to-contributing/</a></p> <p>Even if you are brand new to open-source and WordPress, you are welcome to participate! Bring your questions, thoughts, and comments to this informal discussion hosted by Erica V.</p> ', 32, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-05 08:00:00', '-28800', '2020-11-05 09:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53259995, 'meetup', '274417551', 'scheduled', 'Discussion Group: Contributing on the WordPress Community Team', 'https://www.meetup.com/learn-wordpress-discussions/events/274417551/', '<p>Join us for a discussion on this workshop: Contributing on the WordPress Community Team!</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. Sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/contributing-on-the-wordpress-community-team/\" class=\"linkified\">https://learn.wordpress.org/workshop/contributing-on-the-wordpress-community-team/</a></p> <p>Even if you are brand new to the WordPress Community, you are welcome to participate! Bring your questions, your thoughts, comments to this informal discussion.</p> <p>For more information, visit <a href=\"https://make.wordpress.org/community/\" class=\"linkified\">https://make.wordpress.org/community/</a></p> ', 16, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-07 12:00:00', '-28800', '2020-11-07 13:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53369045, 'meetup', '274495507', 'scheduled', 'Discussion group: Organizing WordPress Meetups - Supporting an Online Meetup', 'https://www.meetup.com/learn-wordpress-discussions/events/274495507/', '<p>Join us for a discussion on this workshop: Organizing WordPress Meetups - Getting Started!</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. In case you don\'t have an account already, sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/organizing-wordpress-meetups-supporting-an-online-meetup/\" class=\"linkified\">https://learn.wordpress.org/workshop/organizing-wordpress-meetups-supporting-an-online-meetup/</a></p> <p>This workshop is geared toward at all WordPress Community members that wish to be a part of the WordPress community, to organize a WordPress meetup. You can join the discussion group even if you are an experienced community organizer. But please watch the topic workshop prior to joining.</p> <p>Bring us all the questions you have, and we\'re happy to answer all questions you have!</p> ', 9, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-10 10:00:00', '-28800', '2020-11-10 12:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53400476, 'meetup', '274203261', 'scheduled', 'Discussion group: Organizing WordPress Meetups - Supporting an Online Meetup', 'https://www.meetup.com/learn-wordpress-discussions/events/274203261/', '<p>Join us for a discussion on this workshop: Organizing WordPress Meetups - Getting Started!</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. In case you don\'t have an account already, sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/organizing-wordpress-meetups-supporting-an-online-meetup/\" class=\"linkified\">https://learn.wordpress.org/workshop/organizing-wordpress-meetups-supporting-an-online-meetup/</a></p> <p>This workshop is geared toward at all WordPress Community members that wish to be a part of the WordPress community, to organize a WordPress meetup. You can join the discussion group even if you are an experienced community organizer.</p> <p>Bring us all the questions you have, and we\'re happy to answer all questions you have!</p> ', 36, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-11 07:00:00', '-28800', '2020-11-11 08:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53439817, 'meetup', '274258067', 'scheduled', 'Discussion Group: Who am I to be speaking? + Finding a topic for a WP event', 'https://www.meetup.com/learn-wordpress-discussions/events/274258067/', '<p>If you are from a marginalized or underrepresented group in WordPress in terms of gender, race, class, sexuality, ability, age, etc. join us for a discussion on this workshop: Who am I to be speaking + Finding a topic.</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-1/\" class=\"linkified\">https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-1/</a></p> <p>We invite you to do the exercises along with the video, and bring your answers to the discussion group to get feedback.</p> <p>This workshop is geared towards people from marginalized or underrepresented groups in WordPress who are intrigued by the idea of speaking at an online WordPress event. The focus is to look at what has stopped you from speaking in the past and explore how to move past your fears, generate WordPress-related topics to give a talk on, and boost your speaking confidence.</p> ', 13, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-12 09:00:00', '-28800', '2020-11-12 10:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53660413, 'meetup', '274559494', 'scheduled', 'Discussion Group: Who am I to be speaking? + Finding a topic for a WP event', 'https://www.meetup.com/learn-wordpress-discussions/events/274559494/', '<p>If you are from a marginalized or underrepresented group in WordPress in terms of gender, race, class, sexuality, ability, age, etc. join us for a discussion on this workshop: Who am I to be speaking + Finding a topic.</p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-1/\" class=\"linkified\">https://learn.wordpress.org/workshop/diverse-speaker-training-workshop-part-1/</a></p> <p>We invite you to do the exercises along with the video, and bring your answers to the discussion group to get feedback.</p> <p>This workshop is geared towards people from marginalized or underrepresented groups in WordPress who are intrigued by the idea of speaking at an online WordPress event. The focus is to look at what has stopped you from speaking in the past and explore how to move past your fears, generate WordPress-related topics to give a talk on, and boost your speaking confidence.</p> ', 20, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-18 09:00:00', '-28800', '2020-11-18 10:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53735284, 'meetup', '274677863', 'scheduled', 'Discussion group: Organizing WordPress Meetups - Supporting an Online Meetup', 'https://www.meetup.com/learn-wordpress-discussions/events/274677863/', '<p>Join us for a discussion on this workshop: Organizing WordPress Meetups - Getting Started!</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. In case you don\'t have an account already, sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/organizing-wordpress-meetups-supporting-an-online-meetup/\" class=\"linkified\">https://learn.wordpress.org/workshop/organizing-wordpress-meetups-supporting-an-online-meetup/</a></p> <p>This workshop is geared toward at all WordPress Community members that wish to be a part of the WordPress community, to organize a WordPress meetup. You can join the discussion group even if you are an experienced community organizer. But please watch the topic workshop prior to joining.</p> <p>Bring us all the questions you have, and we\'re happy to answer all questions you have!</p> ', 34, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-20 10:00:00', '-28800', '2020-11-20 11:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53773073, 'meetup', '274657584', 'scheduled', 'Discussion Group: Contributing on the WordPress Community Team', 'https://www.meetup.com/learn-wordpress-discussions/events/274657584/', '<p>Join us for a discussion on this workshop: Contributing on the WordPress Community Team!</p> <p>Note: We will be hosting this discussion in the Making WordPress Slack in the #community-events channel. Sign-up for an account here: <a href=\"https://make.wordpress.org/chat/\" class=\"linkified\">https://make.wordpress.org/chat/</a></p> <p>To prepare for this discussion, please watch this workshop in advance: <a href=\"https://learn.wordpress.org/workshop/contributing-on-the-wordpress-community-team/\" class=\"linkified\">https://learn.wordpress.org/workshop/contributing-on-the-wordpress-community-team/</a></p> <p>Even if you are brand new to the WordPress Community, you are welcome to participate! Bring your questions, your thoughts, comments to this informal discussion.</p> <p>For more information, visit <a href=\"https://make.wordpress.org/community/\" class=\"linkified\">https://make.wordpress.org/community/</a></p> ', 15, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-21 11:00:00', '-28800', '2020-11-21 12:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53851494, 'meetup', '274764346', 'scheduled', 'Discussion Group: WordPress Troubleshooting Basics', 'https://www.meetup.com/learn-wordpress-discussions/events/274764346/', '<p>Join us for a discussion on this workshop: WordPress Troubleshooting Basics.</p> <p>The event is happening on November 27, 2020 (Friday) at 14:00 UTC: <a href=\"https://www.timeanddate.com/worldclock/fixedtime.html?iso=20201127T1400\" class=\"linkified\">https://www.timeanddate.com/worldclock/fixedtime.html?iso=20201127T1400</a></p> <p>To prepare for this discussion, please watch these workshops in advance: <a href=\"https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-1/\" class=\"linkified\">https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-1/</a><br/><a href=\"https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-2-troubleshooting-with-logs/\" class=\"linkified\">https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-2-troubleshooting-with-logs/</a></p> <p>These workshops cover the basics of WordPress troubleshooting. It is aimed at a beginner audience and will cover the strategy to troubleshoot WordPress issues, along with some common troubleshooting steps that will help in fixing many common WordPress issues.</p> <p>Please watch the videos first and join us for a discussion to answer any questions that you have on troubleshooting WordPress.</p> ', 11, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-11-27 06:00:00', '-28800', '2020-11-27 07:00:00', 'online', 'US', 37.779998779297, -122.41999816895),
(53851495, 'meetup', '274764825', 'scheduled', 'Discussion Group: WordPress Troubleshooting Basics', 'https://www.meetup.com/learn-wordpress-discussions/events/274764825/', '<p>Join us for a discussion on this workshop: WordPress Troubleshooting Basics.</p> <p>The event is happening on December 2, 2020 (Wednesday) at 16:00 UTC: <a href=\"https://www.timeanddate.com/worldclock/fixedtime.html?iso=20201202T1600\" class=\"linkified\">https://www.timeanddate.com/worldclock/fixedtime.html?iso=20201202T1600</a></p> <p>To prepare for this discussion, please watch these workshops in advance: <a href=\"https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-1/\" class=\"linkified\">https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-1/</a><br/><a href=\"https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-2-troubleshooting-with-logs/\" class=\"linkified\">https://learn.wordpress.org/workshop/wordpress-troubleshooting-basics-part-2-troubleshooting-with-logs/</a></p> <p>These workshops cover the basics of WordPress troubleshooting. It is aimed at a beginner audience and will cover the strategy to troubleshoot WordPress issues, along with some common troubleshooting steps that will help in fixing many common WordPress issues.</p> <p>Please watch the videos first and join us for a discussion to answer any questions that you have on troubleshooting WordPress.</p> ', 4, 'Learn WordPress Discussions', 'https://www.meetup.com/learn-wordpress-discussions/', '2020-12-02 08:00:00', '-28800', '2020-12-02 09:00:00', 'online', 'US', 37.779998779297, -122.41999816895);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `wporg_events`
--
ALTER TABLE `wporg_events`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `event_source_id` (`type`,`source_id`),
  ADD UNIQUE KEY `event_type_url` (`type`,`url`(255)),
  ADD KEY `date` (`date_utc`),
  ADD KEY `country` (`country`),
  ADD KEY `lat_lon` (`latitude`,`longitude`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `wporg_events`
--
ALTER TABLE `wporg_events`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53852946;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
