<?php
/**
 * Add elements or adjust the layout for the sensei quiz page.
 */

namespace WordPressdotorg\Theme\Learn_2024\SENSEI_QUIZ;

defined( 'WPINC' ) || die();

/**
 * Actions and filters.
 */
add_action( 'init', __NAMESPACE__ . '\init' );

/**
 * Add a script to update the styles of the sensei quiz page.
 *
 * The dependencies are autogenerated in block.json, and can be read with
 * `wp_json_file_decode` & `register_block_script_handle.
 */
function init() {
	$metadata_file = dirname( dirname( __DIR__ ) ) . '/build/sensei-quiz/block.json';
	$metadata = wp_json_file_decode( $metadata_file, array( 'associative' => true ) );
	$metadata['file'] = $metadata_file;

	$script_handle = register_block_script_handle( $metadata, 'viewScript', 0 );

	// Enqueue the assets when the single quiz template is used.
	add_action(
		'wp_enqueue_scripts',
		function() use ( $script_handle ) {
			if ( is_singular( 'quiz' ) ) {
				$lesson_id = Sensei()->quiz->get_lesson_id();
				$lesson_link = get_permalink( $lesson_id );

				wp_enqueue_script( $script_handle );
				wp_localize_script( $script_handle, 'lesson', array( 'link' => $lesson_link ) );
			}
		}
	);
}
