name: Build and push to build branch.

on:
  push:
    branches: [trunk]
  workflow_dispatch:

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write # Required to push the build branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: trunk
          persist-credentials: false

      - name: Install svn
        shell: bash
        run: |
          sudo apt install subversion

      - name: Install NodeJS
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "8.3"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install php dependencies
        shell: bash
        run: |
          composer install || composer update wporg/*

      - name: Git reset and clean
        run: |
          git reset --hard
          git clean -f -d

      - name: Setup configs
        shell: bash
        run: |
          yarn setup:tools

      - name: yarn install and build
        run: |
          yarn
          yarn workspaces run build

      - name: Trim the repo down to just the source and built files
        run: |
          rm -rf wp-content/mu-plugins/pub/locale-switcher/node_modules
          rm -rf wp-content/plugins/wporg-learn/node_modules
          rm -rf wp-content/themes/pub/wporg-learn-2024/node_modules
          mv wp-content/mu-plugins/pub/locale-switcher $RUNNER_TEMP
          mv wp-content/mu-plugins/pub/class-validator.php $RUNNER_TEMP
          mv wp-content/mu-plugins/pub/locales.php $RUNNER_TEMP
          mv wp-content/mu-plugins/pub/wporg-learn-cli.php $RUNNER_TEMP
          mv wp-content/plugins/polylang-pro $RUNNER_TEMP
          mv wp-content/plugins/sensei-pro $RUNNER_TEMP
          mv wp-content/plugins/wporg-learn $RUNNER_TEMP
          mv wp-content/themes/pub/wporg-learn-2024 $RUNNER_TEMP
          git rm -rfq .
          rm -rf *
          mkdir -p wp-content/mu-plugins/pub
          mkdir -p wp-content/plugins
          mkdir -p wp-content/themes/pub
          mv $RUNNER_TEMP/locale-switcher wp-content/mu-plugins/pub
          mv $RUNNER_TEMP/class-validator.php wp-content/mu-plugins/pub
          mv $RUNNER_TEMP/locales.php wp-content/mu-plugins/pub
          mv $RUNNER_TEMP/wporg-learn-cli.php wp-content/mu-plugins/pub
          mv $RUNNER_TEMP/polylang-pro wp-content/plugins
          mv $RUNNER_TEMP/sensei-pro wp-content/plugins
          mv $RUNNER_TEMP/wporg-learn wp-content/plugins
          mv $RUNNER_TEMP/wporg-learn-2024 wp-content/themes/pub

      - name: Add all the files
        run: |
          git add * --force

      - name: Append build number to version
        run: |
          current_version=$(grep -oP 'Version: \K[0-9]+\.[0-9]+\.[0-9]+' wp-content/themes/pub/wporg-learn-2024/style.css)
          new_version="${current_version}-${GITHUB_SHA::7}"
          sed -i "s/Version: $current_version/Version: $new_version/" wp-content/themes/pub/wporg-learn-2024/style.css

      - name: Commit and push
        uses: actions-js/push@968f4695ca558093eadb24ad83cc5891f47e0cdc # v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build
          force: true
          message: 'Build: ${{ github.sha }}'
