# This was based on https://docs.github.com/en/actions/managing-issues-and-pull-requests/commenting-on-an-issue-when-a-label-is-added

name: Add the applicable content development checklist based on a command in the issue body
on:
  issues:
    types:  opened
    # types: [opened, edited] <= Use this if we want the workflow to run when an issue is edited, too

jobs:
  tutorial-issue:
    if: ${{ contains(github.event.issue.body, '//tutorial') }}
    uses: ./.github/workflows/comment-with-checklist.yml
    with:
      content-type: 'tutorial'
      
  online-workshop-issue:
    if: ${{ contains(github.event.issue.body, '//online-workshop') }}
    uses: ./.github/workflows/comment-with-checklist.yml
    with:
      content-type: 'online-workshop'
  
  lesson-plan-issue:
    if: ${{ contains(github.event.issue.body, '//teach') }}
    uses: ./.github/workflows/comment-with-checklist.yml
    with:
      content-type: 'teach'
  
  course-issue:
    if: ${{ contains(github.event.issue.body, '//course') }}
    uses: ./.github/workflows/comment-with-checklist.yml
    with:
      content-type: 'course'

  lesson-issue:
    if: ${{ contains(github.event.issue.body, '//lesson') }}
    uses: ./.github/workflows/comment-with-checklist.yml
    with:
      content-type: 'lesson'
