# This was based on https://docs.github.com/en/actions/managing-issues-and-pull-requests/commenting-on-an-issue-when-a-label-is-added

name: Add the applicable content development checklist based on a command in the issue body
on:
  issues:
    types:  [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  tutorial-issue:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'Awaiting Triage') && ( contains(github.event.issue.body, '#tutorial#') || contains(github.event.comment.body, '#tutorial#') ) }}
    steps:
    - uses: ./.github/workflows/comment-with-checklist.yml
      with:
        content-type: 'tutorial'
    - uses: ./.github/workflows/add-label.yml
      with:
        label-name: 'Awaiting Triage'
        
  online-workshop-issue:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'Awaiting Triage') && ( contains(github.event.issue.body, '#online-workshop#') || contains(github.event.comment.body, '#online-workshop#') ) }}
    steps:
    - uses: ./.github/workflows/comment-with-checklist.yml
      with:
        content-type: 'online-workshop'
    - uses: ./.github/workflows/add-label.yml
      with:
        label-name: 'Awaiting Triage'
  
  lesson-plan-issue:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'Awaiting Triage') && ( contains(github.event.issue.body, '#lesson-plan#') || contains(github.event.comment.body, '#lesson-plan#') ) }}
    steps:
    - uses: ./.github/workflows/comment-with-checklist.yml
      with:
        content-type: 'lesson-plan'
    - uses: ./.github/workflows/add-label.yml
      with:
        label-name: 'Awaiting Triage'
  
  course-issue:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'Awaiting Triage') && ( contains(github.event.issue.body, '#course#') || contains(github.event.comment.body, '#course#') ) }}
    steps:
    - uses: ./.github/workflows/comment-with-checklist.yml
      with:
        content-type: 'course'
    - uses: ./.github/workflows/add-label.yml
      with:
        label-name: 'Awaiting Triage'
