name: I18n

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:

jobs:
  translation-strings:
    name: Translation strings

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: fix/update-translation-strings

      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:v2

      - name: Install dependencies
        run: composer install

      - name: Run translation script
        run: php ./bin/i18n.php

      - name: Commit and push
        # Using a specific hash here instead of a tagged version, for risk mitigation, since this action modifies our repo.
        uses: actions-js/push@a52398fac807b0c1e5f1492c969b477c8560a0ba
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: fix/update-translation-strings
          message: Update translation strings
