name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
  push:
    branches: [trunk]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: All

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Fetch wporg parent theme css
      run: |
        mkdir wp-content/themes/pub/wporg
        svn export https://meta.svn.wordpress.org/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg/css wp-content/themes/pub/wporg/css

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: yarn install and build
      run: |
        yarn
        yarn workspaces run build

    - name: Lint JavaScript and Styles
      run: |
        yarn workspaces run lint:js
        yarn workspaces run lint:css

    - name: composer install
      run: |
        composer install

    - name: Lint PHP
      run: |
        composer run lint

