name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
  push:
    branches: [trunk]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: composer install
      run: |
        composer install

    - name: Git reset and clean
      run: |
        git reset --hard
        git clean -f -d

    - name: Setup tools
      run: |
        yarn setup:tools

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: yarn install and build
      run: |
        yarn
        yarn build

    - name: Lint JavaScript and Styles
      run: |
        yarn lint:js
        yarn lint:css

    - name: Lint PHP
      run: |
        yarn lint:php
